require 'vagrant'
require 'zmq'
# client
require 'moneta'
require 'vagrant_dns/consts'
require 'vagrant_dns/configuration'
require 'vagrant_dns/middleware/update'
require 'vagrant_dns/middleware/remove'
require 'vagrant_dns/middleware/network_binder'
